### ISSUE TITLE
AndroidElementNotAllowed and now Preview

### ISSUE THREAD

**Issue by chrisonline** [h6ah4i/android-numberpickerprefcompat#1] opened 2019-02-26 12:54 UTC
Hi!

Thanks for your library.
When I add it to my XML I get "**AndroidElementNotAllowed**" and the whole preview does not work anymore inside Android Studio. Otherwise all is working fine.

Can you fix this or let me know if I made a mistake.

`<com.h6ah4i.android.preference.NumberPickerPreferenceCompat   
        android:key="@string/P_CLEAN_UP_DAYS_INT"  
        android:summary="@string/summary_clean_up_days"  
        android:title="@string/clean_up_days"  
        app:nppc_maxValue="999"  
        app:nppc_minValue="1"  
        android:defaultValue="60" />`

Best Regards
Christian

**Comment by Krxwallo** [comment] 2021-08-19 12:21
For anyone having the same issue: You have to add it to your preferences xml and not to your layout xml. See [android developer settings guide](https://developer.android.com/guide/topics/ui/settings.html)

**Comment by h6ah4i** [comment] 2021-08-21 03:01
@Krxwallo Thank you for pinpointing the cause. I'll close this issue.

**Closed as completed by h6ah4i** 2021-08-21 03:01 UTC
